Can't build GeoIP on MS Windows, missing GeoIP.h
   py_GeoIP.c(23): fatal error C1083: Cannot open include file: 'GeoIP.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for GeoIP